### PR TITLE
Build Linux/OSX for Py3.6 as well

### PR DESCRIPTION
**Pull request by cmutel**

### CODE REVIEW

**Comment by stuertz** [comment]
Hi, I would suggest to rerender instead of manipulating the ci scripts manually.
See: https://github.com/conda-forge/staged-recipes/wiki/conda-smithy-rerender

**Comment by cmutel** [comment]
Thanks @stuertz - rerendering updates a lot of things, but doesn't seem to actually include a build of 3.6!? Is there a way to force this version (which I assume would be helpful for many people).

**Comment by stuertz** [comment]
Hm, Maybe one of the dependecies (e.g. sqlite in that specific version) could not be fulfilled. 

This is what the travis build log also says: 
The following specifications were found to be in conflict:
  - python 3.6* -> sqlite 3.13.*
  - sqlite 3.16.2

This is very awkward in this case. The Build file of apsw requires a specific version. So I think rerrendering the sqlite 3.16.2 to support py36, and then rerendering this would help.

**Comment by cmutel** [comment]
OK, this is already outside the scope of this PR. I will make an issue instead.

**Pull request closed without merging**
